---

- name: "Patch INI entry: {{ ini_item.key }}"
  community.general.ini_file:
    path: "{{ _volume_mountpoint }}/{{ patch_item.file | regex_replace('^/+', '') }}"
    section: "{{ patch_item.section | default(omit) }}"
    option: "{{ ini_item.key }}"
    value: "{{ ini_item.value }}"
    no_extra_spaces: true
    mode: "{{ patch_item.mode | default('0644') }}"
  loop: "{{ patch_item.set | dict2items }}"
  loop_control:
    loop_var: ini_item
    label: "{{ ini_item.key }}={{ ini_item.value }}"
