- name: Converge podman-quadlet role
  hosts: localhost
  connection: local
  tasks:

    # rootless
    - name: Stop nginx rootless container # noqa: ignore-errors
      become: true
      ansible.builtin.shell:
        cmd: |
          su - nginx -c '
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
          systemctl --user stop nginxrootless
          '
        executable: /bin/bash
      ignore_errors: true
      changed_when: false

    - name: Remove rootless volume # noqa: ignore-errors,no-changed-when
      become: true
      ansible.builtin.shell:
        cmd: |
          su - nginx -c '
          podman volume rm nginxrootless-volume
          '
        executable: /bin/bash
      ignore_errors: true
      changed_when: false

    - name: Remove rootless quadlet file # noqa: ignore-errors
      become: true
      ansible.builtin.file:
        path: "/home/nginx/.config/containers/systemd/nginxrootless"
        state: absent
      ignore_errors: true

    - name: Reload rootless systemd # noqa: no-ignore-errors,no-changed-when
      become: true
      ansible.builtin.shell:
        cmd: |
          su - nginx -c '
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
          systemctl --user daemon-reload
          '
        executable: /bin/bash
      ignore_errors: true
      changed_when: false

    # rootful
    - name: Stop rootful nginx container # noqa: ignore-errors,command-instead-of-module,no-changed-when
      become: true
      ansible.builtin.shell: |
        systemctl stop nginxrootful
      ignore_errors: true

    # noqa: ignore-errors,no-changed-when
    - name: Remove rootful volume 
      become: true
      ansible.builtin.shell: |
        podman volume rm nginxrootful-volume
      ignore_errors: true

    - name: Remove rootful quadlet file # noqa: ignore-errors
      become: true
      ansible.builtin.file:
        path: "/etc/containers/systemd/nginxrootful"
        state: absent
      ignore_errors: true

    - name: Reload rootful systemd # noqa: command-instead-of-module,no-changed-when
      become: true
      ansible.builtin.shell: |
        systemctl daemon-reload
