---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge podman-quadlet role
  hosts: localhost
  connection: local
  roles:
    - role: podman_quadlet
      podman_quadlet_app_name: nginxrootless
      podman_quadlet_rootless_user_name: nginx
      podman_quadlet_files_templates_src_path: "{{ playbook_dir }}"
      podman_quadlet_file_names:
        - nginxrootless.container.j2
        - nginxrootless.volume
      podman_quadlet_volumes_files_to_stage:
        - name: nginxrootless
          files:
            - src: index.html
            - src: template.html.j2
      podman_quadlet_firewall_ports:
        - 8080/tcp

    - role: podman_quadlet
      podman_quadlet_app_name: nginxrootful
      podman_quadlet_files_templates_src_path: "{{ playbook_dir }}"
      podman_quadlet_file_names:
        - nginxrootful.container
        - nginxrootful.volume
      podman_quadlet_volumes_files_to_stage:
        - name: nginxrootful
          files:
            - src: index.html
            - src: /template/template.html.j2
      podman_quadlet_firewall_ports:
        - 80/tcp
