---
- name: Prepare test system for podman-quadlet
  hosts: localhost
  become: true
  tasks:
    - name: Ensure rootless user exists
      ansible.builtin.user:
        name: nginx
        state: present
        shell: /bin/bash

    - name: Check if linger is enabled for rootless user
      ansible.builtin.command:
        cmd: loginctl list-users
      register: linger_users
      changed_when: false

    - name: Enable linger for rootless user
      ansible.builtin.command:
        cmd: loginctl enable-linger nginx
      when: "'nginx' not in linger_users.stdout.split()"
      changed_when: true

    - name: Ensure podman is installed
      ansible.builtin.package:
        name: podman
        state: present
