---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify container is running
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    # rootless
    - name: Check if rootless nginx container exists
      become: true
      ansible.builtin.shell:
        cmd: |
          su - nginx -c 'podman ps --filter "name=nginxrootless" --format "{% raw %}{{.Names}}{% endraw %}"'
        executable: /bin/bash
      register: nginx_rootless_status
      ignore_errors: true # noqa: ignore-errors
      failed_when: false
      changed_when: false # noqa: no-changed-when

    - name: Assert rootless container is running
      ansible.builtin.assert:
        that:
          - "'nginxrootless' in nginx_rootless_status.stdout"

    - name: Check rootless nginx HTTP response
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:8080"
        return_content: true
        status_code: 200
      register: nginx_rootless_response

    - name: Assert the rootless nginx default page content
      ansible.builtin.assert:
        that:
          - "'Welcome to nginx rootless container test page!' in nginx_rootless_response.content"
        fail_msg: "Nginx page did not contain expected content!"

    - name: Check rootless nginx HTTP response for rendered template
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:8080/template.html"
        return_content: true
        status_code: 200
      register: nginx_rootless_response

    - name: Assert the rootless nginx template page content
      ansible.builtin.assert:
        that:
          - "'Welcome to nginx rootless container template test page!' in nginx_rootless_response.content"
        fail_msg: "Rootless template page did not contain expected content!"

    # rootful
    - name: Check if rootful nginx container exists
      become: true
      ansible.builtin.command:
        cmd: podman ps --filter "name=nginxrootful" --format "{% raw %}{{.Names}}{% endraw %}"
      register: nginx_rootful_status
      ignore_errors: true # noqa: ignore-errors
      failed_when: false
      changed_when: false # noqa: no-changed-when

    - name: Assert rootful container is running
      ansible.builtin.assert:
        that:
          - "'nginxrootful' in nginx_rootful_status.stdout"

    - name: Check rootful nginx HTTP response
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}"
        return_content: true
        status_code: 200
      register: nginx_rootful_response

    - name: Assert the rootful nginx default page content
      ansible.builtin.assert:
        that:
          - "'Welcome to nginx rootful container test page!' in nginx_rootful_response.content"
        fail_msg: "Nginx page did not contain expected content!"

    - name: Check rootless nginx HTTP response for rendered template
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}/template/template.html"
        return_content: true
        status_code: 200
      register: nginx_rootless_response

    - name: Assert the rootless nginx template page content
      ansible.builtin.assert:
        that:
          - "'Welcome to nginx rootful container template test page!' in nginx_rootless_response.content"
        fail_msg: "Rootful template page did not contain expected content!"
